# Generated by Django 3.1.1 on 2023-10-21 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_delete_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Compliance',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Merchant',
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Provider',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='course',
            new_name='compliance',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff',
            new_name='provider',
        ),
        # migrations.AddField(
        #     model_name='subject',
        #     name='question_title',
        #     field=models.CharField(default=django.utils.timezone.now, max_length=255),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Provider'), (3, 'Merchant')], default=1, max_length=1),
        ),
    ]
